diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE =< 24.02, MMSE =< 0.47.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE =< 24.02, MMSE >  0.47, FunctionalAssessment =< 0.07.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE =< 24.02, MMSE >  0.47, FunctionalAssessment >  0.07, MemoryComplaints =< 0.50, FunctionalAssessment =< 2.77, MMSE =< 2.03, MMSE =< 1.75.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE =< 24.02, MMSE >  0.47, FunctionalAssessment >  0.07, MemoryComplaints =< 0.50, FunctionalAssessment =< 2.77, MMSE =< 2.03, MMSE >  1.75.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE =< 24.02, MMSE >  0.47, FunctionalAssessment >  0.07, MemoryComplaints =< 0.50, FunctionalAssessment =< 2.77, MMSE >  2.03, MMSE =< 10.22, MMSE =< 9.77.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE =< 24.02, MMSE >  0.47, FunctionalAssessment >  0.07, MemoryComplaints =< 0.50, FunctionalAssessment =< 2.77, MMSE >  2.03, MMSE =< 10.22, MMSE >  9.77.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE =< 24.02, MMSE >  0.47, FunctionalAssessment >  0.07, MemoryComplaints =< 0.50, FunctionalAssessment =< 2.77, MMSE >  2.03, MMSE >  10.22.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE =< 24.02, MMSE >  0.47, FunctionalAssessment >  0.07, MemoryComplaints =< 0.50, FunctionalAssessment >  2.77, FunctionalAssessment =< 2.98.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE =< 24.02, MMSE >  0.47, FunctionalAssessment >  0.07, MemoryComplaints =< 0.50, FunctionalAssessment >  2.77, FunctionalAssessment >  2.98, MMSE =< 18.97, FunctionalAssessment =< 3.99.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE =< 24.02, MMSE >  0.47, FunctionalAssessment >  0.07, MemoryComplaints =< 0.50, FunctionalAssessment >  2.77, FunctionalAssessment >  2.98, MMSE =< 18.97, FunctionalAssessment >  3.99.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE =< 24.02, MMSE >  0.47, FunctionalAssessment >  0.07, MemoryComplaints =< 0.50, FunctionalAssessment >  2.77, FunctionalAssessment >  2.98, MMSE >  18.97, ADL =< 1.94.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE =< 24.02, MMSE >  0.47, FunctionalAssessment >  0.07, MemoryComplaints =< 0.50, FunctionalAssessment >  2.77, FunctionalAssessment >  2.98, MMSE >  18.97, ADL >  1.94.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE =< 24.02, MMSE >  0.47, FunctionalAssessment >  0.07, MemoryComplaints >  0.50.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE >  24.02, MemoryComplaints =< 0.50, FunctionalAssessment =< 0.23.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE >  24.02, MemoryComplaints =< 0.50, FunctionalAssessment >  0.23.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE >  24.02, MemoryComplaints >  0.50, BehavioralProblems =< 0.50, ADL =< 0.83.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE >  24.02, MemoryComplaints >  0.50, BehavioralProblems =< 0.50, ADL >  0.83.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL =< 4.68, MMSE >  24.02, MemoryComplaints >  0.50, BehavioralProblems >  0.50.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, ADL =< 5.04, MMSE =< 22.20.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, ADL =< 5.04, MMSE >  22.20.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, ADL >  5.04, MMSE =< 29.00, ADL =< 8.87, ADL =< 8.19, FunctionalAssessment =< 1.44, FunctionalAssessment =< 1.09.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, ADL >  5.04, MMSE =< 29.00, ADL =< 8.87, ADL =< 8.19, FunctionalAssessment =< 1.44, FunctionalAssessment >  1.09.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, ADL >  5.04, MMSE =< 29.00, ADL =< 8.87, ADL =< 8.19, FunctionalAssessment >  1.44, MMSE =< 18.90.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, ADL >  5.04, MMSE =< 29.00, ADL =< 8.87, ADL =< 8.19, FunctionalAssessment >  1.44, MMSE >  18.90.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, ADL >  5.04, MMSE =< 29.00, ADL =< 8.87, ADL >  8.19, ADL =< 8.23.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, ADL >  5.04, MMSE =< 29.00, ADL =< 8.87, ADL >  8.19, ADL >  8.23, MMSE =< 12.62.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, ADL >  5.04, MMSE =< 29.00, ADL =< 8.87, ADL >  8.19, ADL >  8.23, MMSE >  12.62.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, ADL >  5.04, MMSE =< 29.00, ADL >  8.87.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, ADL >  5.04, MMSE >  29.00.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints =< 0.50, BehavioralProblems >  0.50, MMSE =< 23.79, ADL =< 7.58, MMSE =< 7.35.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints =< 0.50, BehavioralProblems >  0.50, MMSE =< 23.79, ADL =< 7.58, MMSE >  7.35, FunctionalAssessment =< 2.04, ADL =< 6.02.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints =< 0.50, BehavioralProblems >  0.50, MMSE =< 23.79, ADL =< 7.58, MMSE >  7.35, FunctionalAssessment =< 2.04, ADL >  6.02.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints =< 0.50, BehavioralProblems >  0.50, MMSE =< 23.79, ADL =< 7.58, MMSE >  7.35, FunctionalAssessment >  2.04.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints =< 0.50, BehavioralProblems >  0.50, MMSE =< 23.79, ADL >  7.58.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints =< 0.50, BehavioralProblems >  0.50, MMSE >  23.79.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints >  0.50, MMSE =< 23.92, ADL =< 6.82, ADL =< 6.47.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints >  0.50, MMSE =< 23.92, ADL =< 6.82, ADL >  6.47.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints >  0.50, MMSE =< 23.92, ADL >  6.82.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment =< 5.00, ADL >  4.68, MemoryComplaints >  0.50, MMSE >  23.92.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, FunctionalAssessment =< 9.89, ADL =< 0.27, ADL =< 0.25, MMSE =< 20.59.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, FunctionalAssessment =< 9.89, ADL =< 0.27, ADL =< 0.25, MMSE >  20.59.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, FunctionalAssessment =< 9.89, ADL =< 0.27, ADL >  0.25.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, FunctionalAssessment =< 9.89, ADL >  0.27, FunctionalAssessment =< 5.11, FunctionalAssessment =< 5.05.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, FunctionalAssessment =< 9.89, ADL >  0.27, FunctionalAssessment =< 5.11, FunctionalAssessment >  5.05.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, FunctionalAssessment =< 9.89, ADL >  0.27, FunctionalAssessment >  5.11, MMSE =< 29.38, FunctionalAssessment =< 8.55, FunctionalAssessment =< 8.53, MMSE =< 2.16.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, FunctionalAssessment =< 9.89, ADL >  0.27, FunctionalAssessment >  5.11, MMSE =< 29.38, FunctionalAssessment =< 8.55, FunctionalAssessment =< 8.53, MMSE >  2.16.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, FunctionalAssessment =< 9.89, ADL >  0.27, FunctionalAssessment >  5.11, MMSE =< 29.38, FunctionalAssessment =< 8.55, FunctionalAssessment >  8.53.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, FunctionalAssessment =< 9.89, ADL >  0.27, FunctionalAssessment >  5.11, MMSE =< 29.38, FunctionalAssessment >  8.55.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, FunctionalAssessment =< 9.89, ADL >  0.27, FunctionalAssessment >  5.11, MMSE >  29.38.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, FunctionalAssessment >  9.89, FunctionalAssessment =< 9.93.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems =< 0.50, FunctionalAssessment >  9.89, FunctionalAssessment >  9.93.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems >  0.50, ADL =< 5.04, MMSE =< 23.99, FunctionalAssessment =< 7.09.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems >  0.50, ADL =< 5.04, MMSE =< 23.99, FunctionalAssessment >  7.09, FunctionalAssessment =< 8.31.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems >  0.50, ADL =< 5.04, MMSE =< 23.99, FunctionalAssessment >  7.09, FunctionalAssessment >  8.31, MMSE =< 13.88.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems >  0.50, ADL =< 5.04, MMSE =< 23.99, FunctionalAssessment >  7.09, FunctionalAssessment >  8.31, MMSE >  13.88.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems >  0.50, ADL =< 5.04, MMSE >  23.99.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems >  0.50, ADL >  5.04, FunctionalAssessment =< 8.66, ADL =< 5.28.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems >  0.50, ADL >  5.04, FunctionalAssessment =< 8.66, ADL >  5.28.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems >  0.50, ADL >  5.04, FunctionalAssessment >  8.66, MMSE =< 19.39, FunctionalAssessment =< 9.37.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems >  0.50, ADL >  5.04, FunctionalAssessment >  8.66, MMSE =< 19.39, FunctionalAssessment >  9.37.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints =< 0.50, BehavioralProblems >  0.50, ADL >  5.04, FunctionalAssessment >  8.66, MMSE >  19.39.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment >  5.00, MemoryComplaints >  0.50, ADL =< 4.77, MMSE =< 23.60, MMSE =< 6.55, MMSE =< 4.78, ADL =< 1.39.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment >  5.00, MemoryComplaints >  0.50, ADL =< 4.77, MMSE =< 23.60, MMSE =< 6.55, MMSE =< 4.78, ADL >  1.39.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints >  0.50, ADL =< 4.77, MMSE =< 23.60, MMSE =< 6.55, MMSE >  4.78.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment >  5.00, MemoryComplaints >  0.50, ADL =< 4.77, MMSE =< 23.60, MMSE >  6.55, ADL =< 3.97.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment >  5.00, MemoryComplaints >  0.50, ADL =< 4.77, MMSE =< 23.60, MMSE >  6.55, ADL >  3.97.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints >  0.50, ADL =< 4.77, MMSE >  23.60.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints >  0.50, ADL >  4.77, BehavioralProblems =< 0.50, FunctionalAssessment =< 9.43, FunctionalAssessment =< 7.12.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints >  0.50, ADL >  4.77, BehavioralProblems =< 0.50, FunctionalAssessment =< 9.43, FunctionalAssessment >  7.12, FunctionalAssessment =< 7.86.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints >  0.50, ADL >  4.77, BehavioralProblems =< 0.50, FunctionalAssessment =< 9.43, FunctionalAssessment >  7.12, FunctionalAssessment >  7.86, FunctionalAssessment =< 8.51, ADL =< 8.14.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints >  0.50, ADL >  4.77, BehavioralProblems =< 0.50, FunctionalAssessment =< 9.43, FunctionalAssessment >  7.12, FunctionalAssessment >  7.86, FunctionalAssessment =< 8.51, ADL >  8.14.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints >  0.50, ADL >  4.77, BehavioralProblems =< 0.50, FunctionalAssessment =< 9.43, FunctionalAssessment >  7.12, FunctionalAssessment >  7.86, FunctionalAssessment >  8.51.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints >  0.50, ADL >  4.77, BehavioralProblems =< 0.50, FunctionalAssessment >  9.43, ADL =< 8.43, MMSE =< 13.80.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints >  0.50, ADL >  4.77, BehavioralProblems =< 0.50, FunctionalAssessment >  9.43, ADL =< 8.43, MMSE >  13.80.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints >  0.50, ADL >  4.77, BehavioralProblems =< 0.50, FunctionalAssessment >  9.43, ADL >  8.43.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 0) :- FunctionalAssessment >  5.00, MemoryComplaints >  0.50, ADL >  4.77, BehavioralProblems >  0.50, ADL =< 7.61.
diagnostic(MMSE, FunctionalAssessment, MemoryComplaints, BehavioralProblems, ADL, 1) :- FunctionalAssessment >  5.00, MemoryComplaints >  0.50, ADL >  4.77, BehavioralProblems >  0.50, ADL >  7.61.
